version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local-data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  api:
    image: docker.io/westbrook/eth-api:latest
    ports:
      - "8080:8080"
    environment:
      CONNECTION_URL: jdbc:postgresql://db:5432/docker
