spring:
  datasource:
    url: ${CONNECTION_URL}
    driver-class-name: org.postgresql.Driver
    username: docker
    password: docker
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
