version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
  api:
    image: docker.io/westbrook/greasy-api:latest
    ports:
      - "8080:8080"
    environment:
      CONNECTION_URL: jdbc:postgresql://db:5432/postgres
