create table if not exists score
(
    id integer generated by default as identity constraint score_pkey primary key,
    initials varchar(255),
    score smallint not null,
    time timestamp
);

-- grant all privileges on database docker to docker;

insert into score(initials, score, time) values ('ETH', 100, CURRENT_TIMESTAMP  - INTERVAL '1 DAY');
insert into score(initials, score, time) values ('ETH', 110, CURRENT_TIMESTAMP  - INTERVAL '2 DAY');
insert into score(initials, score, time) values ('ETH', 15, CURRENT_TIMESTAMP  - INTERVAL '3 DAY');
insert into score(initials, score, time) values ('ETH', 190, CURRENT_TIMESTAMP  - INTERVAL '4 DAY');
insert into score(initials, score, time) values ('ETH', 80, CURRENT_TIMESTAMP  - INTERVAL '5 DAY');
insert into score(initials, score, time) values ('ETH', 95, CURRENT_TIMESTAMP  - INTERVAL '6 DAY');
insert into score(initials, score, time) values ('ETH', 145, CURRENT_TIMESTAMP  - INTERVAL '7 DAY');
insert into score(initials, score, time) values ('ETH', 176, CURRENT_TIMESTAMP  - INTERVAL '8 DAY');
insert into score(initials, score, time) values ('ETH', 82, CURRENT_TIMESTAMP  - INTERVAL '9 DAY');